version: '3.7'
services:
  mysql:
    image: mysql:8.0.41
    restart: always
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  gate-simulator:
    build: ./gate-simulator
    container_name: gate-simulator
    ports:
      - "9999:9999"
    working_dir: /app
    command: npm start
    volumes:
      - ./gate-simulator:/app

volumes:
  mysql-data:
    driver: local
  postgres-data:
    driver: local